# https://medium.com/@bezgachev/6-simple-steps-to-automatically-test-and-deploy-your-javascript-app-to-github-pages-c4c32a34bcb1
# https://docs.travis-ci.com/user/deployment/pages/

language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  api_key:
    secure: "LsNimw+FbbYOsypuFMcSBlaabcq4HacAg092cftA6tKBTbmKNaCJW2T45vVno/feifY5jZKTIPYXg4ogSa1efFN8iChMYgDA0vW5To4KZWsjvHit/sMUbYGicrsNtRg7I4ABc345IbXbjOw+C85iN3LDW6Mewnbcvh6bWUaRsi726ztv5lvy9IKrs78X6559EzL1zNADxST2b0L9AwOZjq7uo+cV/l+yCFk1H9QK/suIrJSiG4uIoRjuZUJ3fyJ2S/0wu8r/wzDQoKdcm+gBHD/63AlKVB94wKRhTTvoBefK+1ifVRMfnCJ2a2OA50D/d9agtmmVCmD7tNQwzXjyKtic8N5c0sxvhBiShn3PqBBUwf/m30pWseWk9t6CtmNPyRH9ewfmFJtE1lpGjlZoHTufbxMjnQP71Ku+B3Y6QKbuzILfzwxBA4FNVn5O+1kkH9IvPrIz14aKBbRkE0/BFTJlI13AiqC2oC82mvSL+HrHSkxFkt1t/o4qPhSL5SkPT65gJFXTHmGmWm3BjrmJTLhf1YEhSVoJsK5mOMKvnMtO/RFsEB45LgO2IP9aLZQA+oTtxHgLFo8sawyTH5ofK2RoTgMiMx7QKQjvAaJxZptB0rnVvMSJScFTVFWXOe2qSoX3aQnLxg5gHD+U/PG/TB+sH1voyuB2ykdA6hrb128="
  provider: pages
  skip_cleanup: true
  github_token: $github-token
  local_dir: build
  on:
    branch: master
